steps:
  # 構建 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA', '-f', 'front-end/Dockerfile', 'front-end']

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'restaurant-map-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA' 