steps:
  # 構建 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurant-map-frontend:$COMMIT_SHA', '-f', 'front-end/Dockerfile', 'front-end']

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/restaurant-map-frontend:$COMMIT_SHA']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'cloudrun.yaml'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/restaurant-map-frontend:$COMMIT_SHA' 