logsBucket: "gs://restaurantmap-logs-bucket"
steps:
  # 構建 Docker 映像 - 測試自動部署
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
      '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/restaurantmap/restaurantmap:latest',
      '-f', 'front-end/Dockerfile', 'front-end']

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/restaurantmap/restaurantmap:latest']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'restaurant-map-frontend'
      - '--image=asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/restaurantmap/restaurantmap:latest'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=VITE_API_URL=https://restaurantmap-255668913932.asia-east1.run.app/api'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/restaurantmap/restaurantmap:latest' 