steps:
  # 構建 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurant-map-frontend:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/restaurant-map-frontend:latest', '-f', 'Dockerfile', '.']

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:latest']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'restaurant-map-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:latest'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/github.com/sammin-code/restaurantmap:latest' 